### ISSUE TITLE
GUI container 

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/vanilla-control-center#153] opened 2023-04-18 23:59 UTC
I have wrote this in a last post, but unfortunately I wrote  this in a wrong section, but I have to say that the Gui to create containers are not functional, this is the error that appears every time when you try to create a container ![Screenshot from 2023-04-18 19-35-24.png](https://user-images.githubusercontent.com/113289722/232929750-ebf3b0ee-21a9-4975-90ba-cbde53f7641c.png)

**Comment by kbdharun** [comment] 2023-04-19 01:44
Duplicate of Vanilla-OS/apx#209

As mentioned there

"You need an internet connection to create containers as it pulls the images from docker hub or the distros registry. From the image you attached above, you seem to have not set network passthrough in virt manager, if you ran the first setup it should have failed at the connection check step due to this."

**Closed as completed** 2023-04-19 01:46 UTC
